version: '3.4'

services:
  redis:
    image: redis:latest
    restart: always
    env_file: ./.env.production
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - docker-service

  mariadb:
    image: mariadb:latest
    restart: always
    env_file: ./.env.production
    ports:
      - $DATABASE_PORT:${DATABASE_PORT}
    environment:
      MARIADB_ROOT_PASSWORD: $DATABASE_PASS
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

  todolist:
    image: todolist
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env.production
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}

      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_PREFIX: ${SESSION_PREFIX}

      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}

      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - $APP_PORT:80
    networks:
      - docker-service
    depends_on:
      - mariadb
      - redis

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
